apiVersion: v1
kind: Service
metadata:
  name: sfu-service
  labels:
    app: sfu-service
spec:
  selector:
    app: sfu-service
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
  - name: rtc-tcp
    port: 5000
    targetPort: rtc-tcp
    protocol: TCP
  type: ClusterIP
